### ISSUE TITLE
Procedure Blocks Not Appering

### ISSUE THREAD

**Issue by FOREVEREALIZE** [ClothCreators/more-apis-support#2]
Well, that's it. The procedure blocks aren't loading. Help. If any further info needed, you can tell me.
Thanks!

**Comment by CrispyChips6660** [comment]
what minecraft version?
what mcreator version?
can you provide any logs from <your user>/.mcreator/logs? (the latest one is mcreator.log)

**Comment by FOREVEREALIZE** [comment]
mc 1.15.2
MCreator 2020.4
[mcreator_2020_09_20-2.log](https://github.com/ClothCreators/more-apis-support/files/5251636/mcreator_2020_09_20-2.log)

**Comment by FOREVEREALIZE** [comment]
IDK if the file is useful
I'm pretty new at this
BTW thanks for the quick response

**Comment by CrispyChips6660** [comment]
I think I know what the problem is. I'll fix it ASAP

**Comment by FOREVEREALIZE** [comment]
thanks

**Comment by FOREVEREALIZE** [comment]
Not related but I recommend support for baubles

**Comment by CrispyChips6660** [comment]
> Not related but I recommend support for baubles

Baubles is a mod for 1.12, which is not supported and therefore not going to be added.

**Comment by FOREVEREALIZE** [comment]
sadness

**Comment by FOREVEREALIZE** [comment]
Can you please answer me when that ASAP arrives?

**Comment by CrispyChips6660** [comment]
in an hour or two.
Apparently a lot of mcreator plugins broke upon update to 2020.4 because of a texts.properties file now mandatory. I'll do my best to fix it and will release a patch when I do.

**Comment by CrispyChips6660** [comment]
screw that, this is a lot harder to fix than I thought, maybe I'll need a day or two...

**Comment by CrispyChips6660** [comment]
[Fixed this in 0.5.1 :)](https://github.com/ClothCreators/more-apis-support/releases/tag/v0.5.1) @felixgames097
