### ISSUE TITLE
JEI BUG 

### ISSUE THREAD

**Issue by MrScautHD** [ClothCreators/more-apis-support#3]
But i have found a Bug in More Api when i Aktive JEI makes this Many errors in the gradle can you fix this?
I think JEI have a new Script:
compileOnly fg.deobf(project.dependencies.create("mezz.jei:jei-${minecraft_version}:${jei_version}:api") {
        transitive = false
    })
    runtimeOnly fg.deobf(project.dependencies.create("mezz.jei:jei-${minecraft_version}:${jei_version}") {
        transitive = false
    })

**Comment by MrScautHD** [comment]
@CrispyChips6660

**Comment by CrispyChips6660** [comment]
...
compile logs please...

**Comment by MrScautHD** [comment]
https://media.discordapp.net/attachments/661755712052920324/764747524249878538/boss_tools_C__Users_Elias_Desktop_Space-BossTools-1.15.2-1.16.2_-_MCreator_2020.5_EAP_35716_11.10.20.png?width=861&height=456

**Comment by CrispyChips6660** [comment]
hmm, this doesn't look like our problem, it's probably your internet.

**Comment by MrScautHD** [comment]
@CrispyChips6660 no its not my internet all have this problem test it self!
