### ISSUE TITLE
[1.12.2] Tinker's Construct Guild

### ISSUE THREAD

**Issue by Goldninja100gn** [ClothCreators/more-apis-support#4]
I became curious about this plugin and tried using it with the 1.12.2 generator plugin for 2020.4. I enabled the Tinker's Construct checkbox in the External APIs selection. It rebuilt the workspace like usual, but I never noticed anything different. I went looking for examples of use or a guild of some sort. Notice the Wiki for this plugin had nothing. 

I was wondering if there are any examples or even a small description of how to use this plugin. All that is given is how to install. 
I've noticed it is also missing guilds/examples/wiki for the other APIs for this plugin as well.

Could you please give some examples or a small description of how to use the plugin for the different APIs?

**Comment by CrispyChips6660** [comment]
This plugin is intended to just add the specified mod as a Gradle dependency, it's intended to be used for Java coders as there is no easy way to code in dependencies manually using MCreator. For the regular user it just adds this mod to your test client, any compatibility must be done by Java.

**Comment by Goldninja100gn** [comment]
Okay thank you for answering my question! that makes more sense
